// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Note: Implement Android, iOS, MacOS if needed
  //! Current configuration (Android, iOS, MacOS): PRODUCTION

  static FirebaseOptions get currentPlatformDebug {
    if (kIsWeb) {
      return webDebug;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get currentPlatformRelease {
    if (kIsWeb) {
      throw Exception("SHOULD NOT HAPPEN! We won't be using firebase on release");
    }
    switch (defaultTargetPlatform) {
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions webDebug = FirebaseOptions(
    apiKey: 'AIzaSyDCMxlK8TANMRX4_y11xn3OxGtFxHp2TyQ',
    appId: '1:520640843087:web:c884e66edea39128ff893a',
    messagingSenderId: '520640843087',
    projectId: 'prosper-dev-f712e',
    authDomain: 'prosper-dev-f712e.firebaseapp.com',
    storageBucket: 'prosper-dev-f712e.appspot.com',
    measurementId: 'G-D0TS28RG14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRCEHq6whcrPO_OEQyAiaSFMoyHe1TVAk',
    appId: '1:520640843087:android:79f3b9c72a5450c1ff893a',
    messagingSenderId: '520640843087',
    projectId: 'prosper-dev-f712e',
    storageBucket: 'prosper-dev-f712e.appspot.com',
  );
}
